
import Header from '@/components/wallet/Header';
import Sidebar from '@/components/wallet/Sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'CELEBUT',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="min-h-screen bg-[#f2f4f7] px-4 py-8">
            <div className="">
                {/* Header */}
                {/* <Header /> */}
                <div className="">
                    <div className="grid grid-cols-3 gap-6">
                        <div className="col-span-1">
                            <Sidebar />
                        </div>
                        <div className="col-span-2 ">
                            {children}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
