import LeftSideBar from '@/components/layout/LeftSideBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RightSideBar from '@/components/layout/RightSideBar';
import Header from '@/components/layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CELEBUT',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#f2f4f7]`}>
       {children}
      </body>
    </html>
  );
}
